- name: Om
  hosts: ec2-13-233-86-176.ap-south-1.compute.amazonaws.com
  remote_user: ec2-user

  tasks:
  -  name: "this is to get host file ... "
     become_user: root
     command: cat /etc/hosts
     register: resultstop

#  -  name: "this is to install java ... "
#     command: sudo yum -y install java-1.8.0-openjdk.x86_64
#     register: resultstart

  -  debug: 
      #var: resultstop.stdout_lines,resultstart.stdout_lines
      var: resultstop.stdout_lines