- name: This is to download and install JAVA over AWS server
  hosts: "{{ hostname1 }}"
  remote_user: ec2-user
  become: yes
  become_user: root
  vars:
   a : 11
   b : 2
   java_version : 9
  tasks:
    - name : Om_JAVA_tasks
      include_tasks: Om_JAVA_tasks.yml
