- name: Install Java programme
  hosts: ec2-18-218-85-244.us-east-2.compute.amazonaws.com
  remote_user: ec2-user

  tasks:
   - debug: 
        msg: "Installing JAVA"
   - import_role:
        name: OmRole_installJava
   - debug:
        msg: "Successfully done"
