- name: Install Java programme
  hosts: ec2-13-233-86-176.ap-south-1.compute.amazonaws.com
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
   - debug: 
        msg: "Installing JAVA"
   - import_role:
        name: OmRole_installJava
   - debug:
        msg: "Successfully done"
