---
# tasks file for OmRole_productStart1
- shell: "ls /root/apache* | tr -s ' ' | cut -d' ' -f9"
  register: apache_name
  become: yes
  become_user: root
- name: This role is for starting the product
  shell: "nohup ./catalina.sh start; echo {{ hostname1 }} >> /tmp/abcd"
  args:
     chdir: "/root/{{ apache_name }}/{{ apache_name }}/bin"
  become: yes
  become_user: root